// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRDLmswoQJV4Jo3AyZNANkQ5xLtW1Mv4Q',
    appId: '1:38133152668:web:ef19677b143d3dd73ce659',
    messagingSenderId: '38133152668',
    projectId: 'u4-ejercicio3-jsonavanzado',
    authDomain: 'u4-ejercicio3-jsonavanzado.firebaseapp.com',
    storageBucket: 'u4-ejercicio3-jsonavanzado.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUzEo2XDo82nchA8tQF01dww14ldj0cqA',
    appId: '1:38133152668:android:898eaf66da55956a3ce659',
    messagingSenderId: '38133152668',
    projectId: 'u4-ejercicio3-jsonavanzado',
    storageBucket: 'u4-ejercicio3-jsonavanzado.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK17sFmgLzLfpwHtSe566WZA93G3yelFE',
    appId: '1:38133152668:ios:8f0ce19ee890e34a3ce659',
    messagingSenderId: '38133152668',
    projectId: 'u4-ejercicio3-jsonavanzado',
    storageBucket: 'u4-ejercicio3-jsonavanzado.appspot.com',
    iosBundleId: 'mx.edu.ittepic.damProyectosimple',
  );
}
